### PR TITLE
[PR] Recommend Points of Interest based on viewer's Personality Traits (from Swipe Page)

### LINKED ISSUE #303: [TASK] Develop recommendation algorithm based on user personality traits
**Description:** Implement a recommendation algorithm that tailors point-of-interest (POI) suggestions to users based on their personality traits. The algorithm should analyze user's personality traits to deliver personalized POIs that align with individual preferences and tendencies.

Task-related to US: #302 
PR resolving this issue: #332

### LINKED ISSUE #333: [TASK] Integrate recommendations into the swipe page UI
**Description:** Integrate personalized point-of-interest (POI) recommendations into the swipe page UI, ensuring the display of up to 3 filtered POIs or fallback defaults.

Task related to US: #302 
PR resolving this issue: #332

### LINKED ISSUE #334: [TASK] Modify database to include Points of Interests schema and link with User schema
**Description:** Update the database schema to include the personality_traits table and user_personality_traits table, and establish the relevant relationships between them for personalized POI recommendations.

Task related to US: #302 
PR resolving this issue: #332

### LINKED ISSUE #337: [TASK] Update the User Profile with the backend for personality traits
This task involved updating the **view profile page**, **edit profile page**, and related **backend routes** to seamlessly integrate personality traits with the user profile. The view profile page was enhanced to dynamically display personality stickers based on traits fetched from the database, ensuring only the relevant stickers are shown for each user. The edit profile page was modified to allow users to select or remove traits and update them in the backend, with proper change detection and file upload functionality for avatars via Supabase. Additionally, backend routes such as `/api/users/user/:id`, `/api/users/fetch-profile-edit`, and `/api/users/update-profile` were updated to fetch and handle personality traits accurately. These changes ensure that personality traits are consistently reflected across the profile and edit pages, providing a smooth user experience.

Task-related to US: #302 
PR resolving this issue: #332

### PR DESCRIPTION
**Pull request by CarsonSSk**
This PR introduces a personalized recommendation algorithm that filters and displays up to 3 points of interest (POIs) tailored to users' personality traits on the swipe page. The implementation ensures users receive relevant POI suggestions based on their preferences when viewing a listing.

### Database Schema

- Created `personality_traits` schema in database to store the list of personality traits that a user can have. 

- Created `user_personality_traits` schema in database to store the mapping of a user with their personality traits. 

- Verified the database schema for `points_of_interest`, `user_personality_traits`, and `listings` to align with the filtering logic and trait mappings.

### Function getPersonalizedPOIsForListing 
- Retrieves user personality traits from the database.

- Maps traits to relevant POI categories using a predefined mapping (`traitToPOIMapping`).
- Filters POIs for a specific listing based on the mapped POI categories.
- Limits the response to 3 POIs. If no matches are found, the function falls back to the first 3 available POIs.
- Incorporates fallback logic for default POIs when no filtered results are available.

### API Endpoint
- Added `/listings/:listingId/personalized-pois` endpoint to fetch filtered POIs for a given user and listing.

### Frontend Integration in Swipe Page
- Fetches personalized POIs using the updated API endpoint.

closes #303 
closes #333 
closes #334 
closes #337

related to #302

### CODE REVIEW

**Comment by CarsonSSk** [comment]
Need to link the Profile Page with the personality trait schemas.

**Comment by CarsonSSk** [comment]
Ran CI pipeline from forked repository with @NicholasWahome's help and all checks passed:
image

**Comment by NicholasWahome** [comment]
@CarsonSSk At the moment I get a preferred listings popup which is good, the only issue I'm encountering is within the code it seems to be fetching id:17 specifically which prevents me from using my own profile. Once this adjustment is reverted. I think the code should work really well! 

From a quick overview the setting of it might be the culprit. But not sure please check the screenshot below: 
Screenshot 2024-11-24 at 5 19 25 PM

**Review by NicholasWahome — CHANGES_REQUESTED** [review]
Please make appropriate changes to link the profiles as 
commented and it should be all good!

**Comment by CarsonSSk** [comment]
Added fix and it now works on my end @NicholasWahome, let me know if it also works on your end.

**Review by NicholasWahome — APPROVED** [review]

**Review by NicholasWahome — APPROVED** [review]
This works as intended my points of interests are the ones matching my preference which is cooking. 
https://github.com/user-attachments/assets/1485ce7a-c243-46a9-a5d5-9cd1eb26b69a

**Pull request merged**
