### PR TITLE
[PR] CI Implementation Base Creation

### PR DESCRIPTION
**Pull request by NicholasWahome**
**Description:** This issue focuses on setting up foundational configurations for the CI/CD pipeline to ensure a standardized and efficient development environment. The current scope includes configuring Docker with docker-compose, setting up ESLint for JavaScript code quality checks, and integrating Prettier for code formatting. These initial configurations will establish consistency and enforce code standards across the project.

Fixed CI issues Related to #19

### CODE REVIEW

**Comment by NicholasWahome** [comment]
@CodePioneerX please update the github secret TOKEN key to enable access to write directly to the repo as well. 
Also just in case what is the name of the TOKEN? If it's not added then prettier will be able to run and we'll have our base set up fully working

**Comment by NicholasWahome** [comment]
In the meatine @CarlaShawi I have added you as reviewer. Please make sure to check the docker section to ensure it conforms to the way you want to run our docker-compose

**Comment by CarlaShawi** [comment]
I just reviewed the branch.  The current docker setup and docker CI integration are aligned, ensuring consistency between the development and CI pipelines.

Also, based on our previous discussion you suggested caching. I believe including a docker layer caching to the CI pipeline is a good idea to speed up image rebuilds and improve overall efficiency during development and testing for future sprints

**Review by CarlaShawi — APPROVED** [review]

**Comment by harismah** [comment]
> y working

Done! The name of the token is set as TOKEN as suggested. Everything looks good on my end, and it meets the requirements set for this sprint. I will now close the issue, thanks!

**Review by harismah — APPROVED** [review]

**Pull request merged**
