### PR TITLE
[PR FIX] Header Responsiveness

### LINKED ISSUE #177: [BUG] Header Responsiveness
**Description:** 
 Header Nav Bar seems to be cut out profile picture when viewing for ipad air.
 
 PR Resolving header issues: #179 & #209 
 
image

For ipad mini, the Nav Bar doesn't show and there's no hamburger button.
image

For Asus Zenbook Fold, the profile icon is cut out.
image

### PR DESCRIPTION
**Pull request by v-vasco**
**Description:**

Fixed display issues with the header where it wouldn't display correctly on devices with a width between 768px and 870px

Relates: #177

### CODE REVIEW

**Comment by CarlaShawi** [comment]
image
image

it is responsive now and it displays properly. Great work!
However, one thing to suggest when users click on the profile page, swipe, or explore, the menu remains open until they manually close it by clicking 'x' affecting the styling of the page
image
@v-vasco

**Comment by v-vasco** [comment]
Here's a mini demo on an Ipad Mini display fixing both the main bug and the issue raised by @CarlaShawi above.

https://github.com/user-attachments/assets/965719f0-817c-4bda-8a6e-668b7114b58e

**Review by NicholasWahome — APPROVED** [review]
As @CarlaShawi has mentionned this is great work and it works as intended. The concern that was brought up by the previous teammate mentioned has now been resolved.

**Comment by CarsonSSk** [comment]
Hey @v-vasco, @CodePioneerX and I noticed that the Dwella logo is significantly smaller on small devices. Here is an example on IPhone SE: 
image

**Comment by harismah** [comment]
Following issues mentioned were later resolved by PR #209

**Pull request merged**
