### PR TITLE
[PR FIX] Improve Explore Page Responsiveness

### PR DESCRIPTION
**Pull request by harismah**
**Description:**

This PR resolves issue #184  by enhancing the Explore Page's responsiveness across various screen sizes, especially on mobile and tablet devices. Adjustments include:
- Refined grid layout for better alignment and spacing on smaller screens.
- Updated filter dropdown and search container positioning.
- Applied responsive typography and padding for consistent readability.
- Improved hover effects and button styling for a more polished look.

### CODE REVIEW

**Comment by harismah** [comment]
Here are some images of the responsiveness in different screen sizes 
Screenshot 2024-10-31 at 2 53 42 PM
Screenshot 2024-10-31 at 2 53 48 PM
Screenshot 2024-10-31 at 3 47 27 PM

**Review by NicholasWahome — CHANGES_REQUESTED** [review]
Unfortunately this is not working on iPad  air configurations... 
Screenshot 2024-10-31 at 3 33 45 PM

**Comment by harismah** [comment]
> Unfortunately this is not working on iPad air configurations... Screenshot 2024-10-31 at 3 33 45 PM

Yes that would need to be addressed under the header bug, as its the header thats not responsive and totally non related to the Explore page bug

**Review by NicholasWahome — APPROVED** [review]
As the header fixture will be fixed in another bug and is unrelated to this one the page responsiveness is perfect across all devices for the explore page. 
The issue number has been updated as well. All checks have passed, so I am reversing my request changes. 
Screenshot 2024-10-31 at 4 09 45 PM

**Comment by harismah** [comment]
Thank You for the PR Review and ensuring any possible issues are addressed

**Pull request merged**
